export const userColor: string[] = [
    'darkcyan',
    'blueviolet',
    'blue',
    'burlywood',
    'chartreuse',
    'coral',
    'crimson',
    'cyan',
    'darkgoldenrod',
    'darkmagenta',
    'darkorange',
    'deeppink',
    'limegreen',
    'magenta',
]